{application,phoenix_ecto,
             [{registered,[]},
              {description,"Integration between Phoenix & Ecto"},
              {applications,[kernel,stdlib,elixir,logger,ecto,phoenix]},
              {vsn,"0.3.0"},
              {modules,['Elixir.Phoenix.Ecto',
                        'Elixir.Phoenix.HTML.FormData.Ecto.Changeset',
                        'Elixir.Phoenix.HTML.Safe.Decimal',
                        'Elixir.Phoenix.HTML.Safe.Ecto.Date',
                        'Elixir.Phoenix.HTML.Safe.Ecto.DateTime',
                        'Elixir.Phoenix.HTML.Safe.Ecto.Time',
                        'Elixir.Poison.Encoder.Decimal',
                        'Elixir.Poison.Encoder.Ecto.Changeset',
                        'Elixir.Poison.Encoder.Ecto.Date',
                        'Elixir.Poison.Encoder.Ecto.DateTime',
                        'Elixir.Poison.Encoder.Ecto.Time']}]}.